CREATE DATABASE IF NOT EXISTS laser;
USE laser;
CREATE TABLE IF NOT EXISTS admins (
    id BINARY(16) NOT NULL PRIMARY KEY UNIQUE,
    password BINARY(60) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);
