CREATE DATABASE IF NOT EXISTS laser;
USE laser;
CREATE TABLE IF NOT EXISTS users (
    id BINARY(16) NOT NULL PRIMARY KEY UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password BINARY(60) NOT NULL,
    email VARCHAR(255),
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255)
);
